export const ROUTES = {
  // Marketing
  HOME: "/",
  FEATURES: "/features",
  PRICING: "/pricing",
  ABOUT: "/about",
  CONTACT: "/contact",
  PRIVACY: "/privacy",
  TERMS: "/terms",

  // Auth
  LOGIN: "/auth/login",
  REGISTER: "/auth/register/step-1",
  REGISTER_STEP: (step: number) => `/auth/register/step-${step}`,
  VERIFY_EMAIL: "/auth/verify-email",
  FORGOT_PASSWORD: "/auth/forgot-password",
  RESET_PASSWORD: "/auth/reset-password",
  ONBOARDING: "/auth/onboarding/step-1",
  ONBOARDING_STEP: (step: number) => `/auth/onboarding/step-${step}`,

  // Owner Dashboard
  DASHBOARD: "/owner/dashboard",
  CONVERSATIONS: "/owner/conversations",
  CONVERSATION_DETAIL: (id: string) => `/owner/conversations/${id}`,
  PRODUCTS: "/owner/products",
  PRODUCT_ADD: "/owner/products/add",
  PRODUCT_DETAIL: (id: string) => `/owner/products/${id}`,
  PRODUCT_EDIT: (id: string) => `/owner/products/${id}/edit`,
  CATEGORIES: "/owner/products/categories",
  LEADS: "/owner/leads",
  LEAD_DETAIL: (id: string) => `/owner/leads/${id}`,
  ORDERS: "/owner/orders",
  ORDER_DETAIL: (id: string) => `/owner/orders/${id}`,
  AI_AGENT: "/owner/ai-agent",
  AI_TRAIN: "/owner/ai-agent/train",
  AI_TEMPLATES: "/owner/ai-agent/templates",
  AI_SETTINGS: "/owner/ai-agent/settings",
  AI_PLAYGROUND: "/owner/ai-agent/playground",
  ANALYTICS: "/owner/analytics",
  ANALYTICS_REVENUE: "/owner/analytics/revenue",
  ANALYTICS_CONVERSATIONS: "/owner/analytics/conversations",
  ANALYTICS_PRODUCTS: "/owner/analytics/products",
  INTEGRATIONS: "/owner/integrations",
  MENTIONS: "/owner/mentions",
  TEAM: "/owner/team",
  SETTINGS: "/owner/settings",
  BROADCASTS: "/owner/broadcasts",
  ACTIVITY: "/owner/activity",
  NOTIFICATIONS: "/owner/notifications",

  // Agent Dashboard
  AGENT_HOME: "/agent/dashboard",
  AGENT_CONVERSATIONS: "/agent/conversations",
  AGENT_LEADS: "/agent/leads",
  AGENT_ORDERS: "/agent/orders",
  AGENT_PRODUCTS: "/agent/products",
  AGENT_PERFORMANCE: "/agent/performance",
  AGENT_PROFILE: "/agent/profile",
} as const;
